language: perl6
perl6:
  - latest
  - '2020.05.1'
os:
  - linux
  - osx
install:
  - rakudobrew build-zef
  - zef --depsonly install .
  - zef build .
script:
  - prove -ve "raku -I."
  - zef install .
