name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-libraries:
    runs-on: windows-latest
    steps:
      - name: Setup
	run: |
	  choco install make
	  choco install mingw
	  refreshenv
      - name: Rebuild DLL
	run: |
	  make -f Makefile.mingw dll # build distribution dll
      - name: Check-in DLL
      - uses: stefanzweifel/git-auto-commit-action@v4
	with:
	  commit_message: Automated Windows DLL save
	  commit_user_name: David Warring
	  commit_user_email: david.warring@gmail.com
	  file_pattern: resources/libraries/base64.dll
	  add_options: -f
  raku:
    needs: build-libraries
    strategy:
      matrix:
        os:
          - ubuntu-latest
          ##- macOS-latest
          - windows-latest
        raku-version:
          - 'latest'
          ##- '2021.08'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Install Dependencies
        run: |
          zef install --/test App::Prove6
          zef install --deps-only .
          zef build .
      - name: Run Tests
        run: prove6 -I. t
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Windows DLL save
          commit_user_name: David Warring
          commit_user_email: david.warring@gmail.com
          file_pattern: resources/libraries/base64.dll
          add_options: -f
